name: Publish Docker image
on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: github.ref == 'refs/heads/master'
        name: Build and push playground-sandbox
        uses: docker/build-push-action@v2
        with:
          context: sandbox
          file: sandbox/Dockerfile
          push: true
          tags: ineva/playground-sandbox:latest

      - if: github.ref == 'refs/heads/main'
        name: Build and push playground-sandbox-gvisor
        uses: docker/build-push-action@v2
        with:
          context: sandbox
          file: sandbox/Dockerfile.gvisor
          push: true
          tags: ineva/playground-sandbox-gvisor:latest
